apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2026-06-21T11:09:40Z"
  generation: 6
  name: springboot-gitops
  namespace: argocd
  resourceVersion: "19766"
  uid: 657d6e1b-8e03-40b6-88fe-5561a2ef2cdd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: Kubernetes
    repoURL: https://github.com/Anuchy/springboot-gitops-cicd-pipeline.git
    targetRevision: main
status:
  conditions:
  - lastTransitionTime: "2026-06-21T11:09:40Z"
    message: 'Failed to load live state: failed to get managed objects: unexpected
      error getting managed object: failed to get api resource: failed to discover
      server resources for group version : groupVersion shouldn''t be empty'
    type: ComparisonError
  controllerNamespace: argocd
  health:
    lastTransitionTime: "2026-06-21T11:09:40Z"
    status: Missing
  operationState:
    finishedAt: "2026-06-21T11:09:50Z"
    message: 'ComparisonError: Failed to load live state: failed to get managed objects:
      unexpected error getting managed object: failed to get api resource: failed
      to discover server resources for group version : groupVersion shouldn''t be
      empty'
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        revision: 9b34243cc584ae9e3d7e7aaa517a5adf0fc4fee1
        source:
          path: Kubernetes
          repoURL: https://github.com/Anuchy/springboot-gitops-cicd-pipeline.git
          targetRevision: main
        syncStrategy:
          hook: {}
    phase: Error
    startedAt: "2026-06-21T11:09:50Z"
    syncResult:
      revision: 9b34243cc584ae9e3d7e7aaa517a5adf0fc4fee1
      source:
        path: Kubernetes
        repoURL: https://github.com/Anuchy/springboot-gitops-cicd-pipeline.git
        targetRevision: main
  reconciledAt: "2026-06-21T11:09:50Z"
  resourceHealthSource: appTree
  resources:
  - kind: Deployment
    name: spring-boot-app
    namespace: default
    status: Unknown
  - kind: Service
    name: spring-boot-service
    namespace: default
    status: Unknown
    version: v1
  sourceHydrator: {}
  sourceType: Directory
  summary: {}
  sync:
    comparedTo:
      destination:
        namespace: default
        server: https://kubernetes.default.svc
      source:
        path: Kubernetes
        repoURL: https://github.com/Anuchy/springboot-gitops-cicd-pipeline.git
        targetRevision: main
    revision: 9b34243cc584ae9e3d7e7aaa517a5adf0fc4fee1
    status: Unknown
