pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('Springboot-app') {
                    sh 'mvn clean package'
                }
            }
        }
    }
}